steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'Dockerfile.prod', '-t', 'us-central1-docker.pkg.dev/project-asistente-openai-juanc/repo-chat-streamlit-datapath/image-v1-streamlit-datapath:latest', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/project-asistente-openai-juanc/repo-chat-streamlit-datapath/image-v1-streamlit-datapath:latest']
images:
  - 'us-central1-docker.pkg.dev/project-asistente-openai-juanc/repo-chat-streamlit-datapath/image-v1-streamlit-datapath:latest'
